// benchmarks/workloads/svelte/src/Todo.svelte
<script>
 let tasks=$state(Array.from({length:20},(_,id)=>({id,title:`Task ${id+1}`,done:false})));
 let title=$state(''),filter=$state('all');
 let done=$derived(tasks.filter(task=>task.done).length);
 let visible=$derived(tasks.filter(task=>filter==='all'||task.done===(filter==='done')));
 function add(event){event.preventDefault();if(!title.trim())return;tasks.push({id:Date.now(),title:title.trim(),done:false});title='';}
</script>
<main><h1>Tasks</h1><form onsubmit={add}><input aria-label="New task" bind:value={title}><button>Add task</button></form><nav>{#each ['all','active','done'] as value}<button onclick={()=>filter=value}>{value}</button>{/each}</nav><p class="task-count">{tasks.length} tasks · {done} done</p><ul>{#each visible as task (task.id)}<li><label><input type="checkbox" bind:checked={task.done}><span>{task.title}</span></label><button aria-label="Delete task" onclick={()=>tasks=tasks.filter(item=>item.id!==task.id)}>×</button></li>{/each}</ul></main>

// benchmarks/workloads/vue/src/Todo.vue
<script setup>
import {ref,computed} from 'vue';
const tasks=ref(Array.from({length:20},(_,id)=>({id,title:`Task ${id+1}`,done:false})));
const title=ref(''),filter=ref('all');
const done=computed(()=>tasks.value.filter(task=>task.done).length);
const visible=computed(()=>tasks.value.filter(task=>filter.value==='all'||task.done===(filter.value==='done')));
function add(){if(!title.value.trim())return;tasks.value.push({id:Date.now(),title:title.value.trim(),done:false});title.value='';}
</script>
<template><main><h1>Tasks</h1><form @submit.prevent="add"><input aria-label="New task" v-model="title"><button>Add task</button></form><nav><button v-for="value in ['all','active','done']" :key="value" @click="filter=value">{{value}}</button></nav><p class="task-count">{{tasks.length}} tasks · {{done}} done</p><ul><li v-for="task in visible" :key="task.id"><label><input type="checkbox" v-model="task.done"><span>{{task.title}}</span></label><button aria-label="Delete task" @click="tasks=tasks.filter(item=>item.id!==task.id)">×</button></li></ul></main></template>
